### ISSUE TITLE
Announce plugin on mailing list

### ISSUE THREAD

**Issue by thibaultcha** [mogui/kong-external-oauth#1]
Hello!

Good job on the plugin! We are happy to see members of the community stepping forward and publishing Kong plugins on Luarocks :)

As of now, we don't offer you yet a way to advertise your plugin on https://getkong.org/plugins, but are planning to in the future. In the meantime, feel free to publish an announcement on the [Kong Mailing List](https://groups.google.com/forum/#!forum/konglayer), as I am sure it will give you some exposition and peak the interest some of the Kong users out there.

```
[ANN] Community Plugin - external-oauth 1.0
```

Just a suggestion :)

Best,
Thibault

**Comment by mogui** [comment]
oh thanks! I will for sure :)
