### ISSUE TITLE
Doesn't work with ACL's

### ISSUE THREAD

**Issue by jdarling** [mogui/kong-external-oauth#3]
I noticed that currently there is no way to utilize external oauth alongside ACL's as the ACL stuff doesn't recognize that auth has been completed.  I'm still digging (deep) through the code to find a resolution, but it seems from my initial poking around that the CONSUMER_ID must be set.

**Comment by mogui** [comment]
Yep and I think it only makes sense for ACL to work with an "internal" authentication.
The whole consumer id thing makes sense for authentication managed by KONG, this plugin delegates the whole auth to a third party, there's no knowledge inside KONG of any user authenticated with this plugin.
I'll close the issue.
