### ISSUE TITLE
Do not call userinfo endpoint every time

### ISSUE THREAD

**Issue by XVincentX** [mogui/kong-external-oauth#5]
As you were correctly writing [here](https://github.com/mogui/kong-external-oauth/blob/master/src/access.lua#L49), I do think that the idea that kong is making an additional (and blocking) http request every time I'm accessing an API is an overkill, thous storing the thing in a cookie is definitely a better idea. Would you be willing to accept a pull request implementing that behaviour?

**Comment by mogui** [comment]
Hi @XVincentX Yes, I would be glad
I think that's overkill too, but it is something that it is needed since it's the only way to verify the token is good, we could store it in a cookie but with a "not so long" expiration time

**Comment by XVincentX** [comment]
Yes, I think you're right.
While this might be a bit inefficient, now that I think a little bit more about that I think that for security reasons it's the best way to request for user info for almost every request.

If I would revoke the authorisation from my side, Kong would continue to serve the content even though it should not.

The problem is - defining a **short enough** value; I would say the best way would be to set the expiration as a configuration parameter and give a reasonable default (like 60 seconds); what do you think?

**Comment by mogui** [comment]
> If I would revoke the authorisation from my side, Kong would continue to serve the content even though it should not.

That is the point yes :)

> I would say the best way would be to set the expiration as a configuration parameter and give a reasonable default (like 60 seconds); what do you think?

I think 60 seconds and being configurable should be ok

**Comment by XVincentX** [comment]
Cool - there's a PR for that!
