### ISSUE TITLE
Big overhead

### ISSUE THREAD

**Issue by XVincentX** [mogui/kong-external-oauth#7]
I just made some performance tests:

```bash
Percentage of the requests served within a certain time (ms)
  50%      2
  66%      3
  75%      3
  80%      3
  90%      3
  95%      3
  98%      4
  99%      5
 100%      8 (longest request)
```

With the plugin:

```bash
Percentage of the requests served within a certain time (ms)
  50%     61
  66%     70
  75%     78
  80%     83
  90%    118
  95%    157
  98%    238
  99%    352
 100%    455 (longest request)
```

The impact seems to be really noticeable and I think we could cache some things around and not compute these every single time. I'll try to look into that!

**Comment by mogui** [comment]
oh fuck! it's because of the sync call to verify the token, I think it cannot be avoided.
Maybe there's some more performant way to do the http call? 
your latest pull request with the time based check improved these benck?

**Comment by XVincentX** [comment]
With the PR merged, these are the new times:

```bash
Percentage of the requests served within a certain time (ms)
  50%      3
  66%      3
  75%      4
  80%      4
  90%      5
  95%      7
  98%     11
  99%     20
 100%     87 (longest request)
```

Much better I'd say.
